extends Task

class_name Fail

func run():
	fail()
